apiVersion : apps/v1
kind: Deployment
metadata:
  name: "collloginportal-3964"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "collloginportal-3964"
  template:
    metadata:
      labels:
        app: "collloginportal-3964"
    spec:
      containers:
        - name: "collloginportal-3964"
          image: "collloginportal02.azurecr.io/collloginportal"
          ports:
          - containerPort: 80