apiVersion: v1
kind: Service
metadata:
    name: "collloginportal-42de"
    labels:
        app: "collloginportal-42de"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "collloginportal-42de"